### ISSUE TITLE
Provide class name / model_name

### ISSUE THREAD

**Issue by Darhazer** [Paxa/light_record#3]
I'm trying to integrate light_record into ActiveAdmin. One of the problems that I faced is that the [arbe views](https://github.com/activeadmin/arbre) try to use the class name of the record, resulting in `Class name cannot be blank. You need to supply a name argument when anonymous class given` error.

Here is the relevant code from arbe:

 ```ruby
def dom_class_name_for(record)
   if record.class.respond_to?(:model_name)
     record.class.model_name.singular
   else
     record.class.name.underscore.gsub("/", "_")
   end
end

```
Here is a sample implementation that resolves this specific issue:

```ruby
def build_for_class(klass, fields)
  new_klass = Class.new(klass) do
    define_singleton_method(:model_name) do
      klass.model_name
    end
   ...
  end
end
```

**Comment by Paxa** [comment]
Thank you for feedback, should be fixed by https://github.com/Paxa/light_record/commit/1e0e8c411625c9407c61b709d6c91c3fda5df783#diff-c4563fcc106b17bfd989af308f57b107

I'm curious to know, do you have any performance improvements with light_record in active_admin?

btw you can extend new class by adding `LightRecord` module to a model class:
```ruby
class User < ActiveRecord::Base
  module LightRecord
    def self.included(base)
      base.extend(ClassMethods)
    end
    module ClassMethods
      def im_a_class_method
        :pam_param_pam_pam
      end
    end
  end
end
```

**Comment by Darhazer** [comment]
Thank you!

Whether there is a performance improvements with light_record is the question I'm trying to answer. I still have some issues integrating it (I'm unable to access relations, and there is a lot of cases where the views show attribute from a relation). I have some other possible use cases for light_record, so I'll be happy to share benchmarks once I've integrated it in any part of our system.

**Comment by Darhazer** [comment]
I didn't get any performance improvement in ActiveAdmin - guess is to be expected as only 30 records are shown. I'm closing the issue as what was described is fixed, and if I get any further feedback / benchmarks in other code - I'll open new one to share the feedback.

**Comment by Paxa** [comment]
Thank you for information

Usually I don't have any performance problems in ActiveAdmin, but LightRecord can be useful for generating csv/json/xml file to download, it's gonna process a lot of records there.

Once I notice ActiveAdmin become much slower when working with bigger tables, problem was with kaminari running `select count(*) ...` query, solved by checking only next 5 pages instead of everything.

**Comment by blakewest** [comment]
@Paxa I still get this same issue for associations of a given light record. For example, I use [rabl](https://github.com/nesquena/rabl) for generating JSON on our API. Whenever our JSON view calls for a relationship (ie. Invoice --> Payment), I see the same error `Class name cannot be blank. You need to supply a name argument when anonymous class given`. I'm not sure if there's an easy fix here. But it also sounded like LightRecord doesn't work with associations? Is there a good way to make this happen? I'd love to be able to benchmark this, and see if it helps. It seems like a great concept.

**Comment by Paxa** [comment]
Hi, it wasn't published as gem yet, are you using latest one from git?
Can you give example of db structure?

**Comment by Paxa** [comment]
I added example for relations and some fix for that https://github.com/Paxa/light_record/blob/master/examples/relations.rb

But it will not work with `includes`, if you have only `belongs_to` and `has_one` relations then it will work faster if you load it with one request using some custom sql
